name: pipeline
version: '1.0.0'

profile: pipeline

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  pipeline:
    datacenter_facilities:
      +column_types:
        lat: float8
        lon: float8
        capacity_mw_est: float8
        year_opened: integer

models:
  pipeline:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts
